### ISSUE TITLE
Problem with camera view in "RecognitionResultOnImage" in Autoware

### ISSUE THREAD

**Issue by FrancescoSantorelli001** [TUMFTM/Carla-Autoware-Bridge#14]
Hi, I reproduced step by step the tutorial found on youtube. After running carla, bridge and starting autoware, I see correctly the vehicle placed in autoware and in the RecognitionResultOnImage box there is the correct image. After selecting the path and starting the simulation, the vehicle moves correctly in both autoware and carla but the image in RecognitionResultOnImage remains stuck at the initial frame. Is this a problem with the camera? Do you have a solution to the problem? Thanks in advance

**Comment by TUMGEKA** [comment]
We could not reproduce that error with Autoware 2024.05. Could you retry it with the newest version? Nevertheless the autoware traffic light detection depends on a correct traffic light position in the lanelet2. Our maps currently do not have traffic light integration
