### ISSUE TITLE
Performance Issues when using the Bridge

### ISSUE THREAD

**Issue by MarioAlmelaUMH** [TUMFTM/Carla-Autoware-Bridge#17]
Hello, I'm currently working with Carla and Autoware using this Bridge, and I'm encountering really severe performance issues. Autoware seems almost frozen and scripts like the `generate_traffic.py` always crash due to timeouts. After 2.5 hours, the simulation only triggered 171 ticks (50 ms). Here's some considerations to take into account:

**Computer Specs**
- Ubuntu 22.04
-  64 GB of Memory
-  Intel Core i9-9980XE CPU @ 3.00 GHz with 36 cores
- 2 Nvidia Quadro P4000 GPUs 

**Carla**
- Carla is making one of my CPU cores work always at 100%. I believe Carla is the responsible of this because the problem persists even when I shut down everything else, and resolves once I shut down Carla.
![CPU_collapsed_core](https://github.com/TUMFTM/Carla-Autoware-Bridge/assets/119304913/362d933e-213d-40e3-bc0c-198ebeba303f)
- I'm currently using options like `-RenderOffScreen` and `-quality-level=Low` for performance.

**Autoware**
- Because of the project I'm working on, I need to record plenty of data from the Carla-Autoware simulations. I'm using `ros2bag` to record around 30 Autoware topics.
- I'm using a custom sensor kit based on the default bridge's sensor kit. In this case, I removed the rear lidar, but added two RGB 2k Cameras, with their respective Tensorrt_yolo processes.
- Both Tensorrt_yolo processes are running in the second GPU, while the rest of processes run in the fist one, according to `nvidia-smi`.

These performance issues seem completely anomalous. Is there any performance option I may have missed? I'm following the commands shown in the main README file to start everything, but maybe some configuration options in Carla or Autoware are preventing the platform from properly using the GPU or consume more resources than needed.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by TUMGEKA** [comment]
Hello, Mario!

I've received similar feedback from individuals utilizing a Quadro GPU. I believe that your GPUs may be the bottleneck. CARLA is built on the UNREAL Engine for efficient computation, making gaming GPUs like those from the GeForce RTX series particularly suitable.

**Comment by MarioAlmelaUMH** [comment]
I see. I'll take it into account. Despite the GPUs not being RTX, is there any other performance increasing option that I should try?

**Comment by TUMGEKA** [comment]
I can suggest you the following:

- use the low quality setting for carla
- spawn lidar points with less points per second
- use town01 instead of town10

**Comment by MarioAlmelaUMH** [comment]
Thank you for the suggestions. We are considering trying the RTX GPUs. For now, I'll close this thread and I'll reopen it if the problem persists with the new GPUs.
