### ISSUE TITLE
[Help Need]  any other lanelet2 maps or the method to modify maps

### ISSUE THREAD

**Issue by tk-menot** [TUMFTM/Carla-Autoware-Bridge#18]
Do you have any other lanelet2 maps, my project need other maps?
I saw that you used software for conversion, and I also saw that the paper mentioned the need for manual modification. May I ask if you have any experience and methods in modifying maps?

**Comment by TUMGEKA** [comment]
@tk-menot We have uploaded more maps into sync and share, we will continue in the following days. For the very large maps we will wait until the autoware partial lanelet2 loading is merged: https://github.com/autowarefoundation/autoware.universe/pull/6241
