### ISSUE TITLE
Question Regarding Carla Synchronous Mode

### ISSUE THREAD

**Issue by YuqiHuai** [TUMFTM/Carla-Autoware-Bridge#19]
Thank you so much for providing this awesome bridge between Carla and Autoware!

I am currently trying to study the implication of using Carla's synchronized mode based on [this](https://carla.readthedocs.io/en/latest/adv_synchrony_timestep/#client-server-synchrony) documentation.

**Q1**: Is there a specific configuration of Carla that we must use (e.g., synchronous mode with fixed time-step) for this bridge to work properly?

Looks like by default, Carla runs in asynchronous mode, and I assume that is the default option preferred by this bridge.

**Q2**: Do you see any potential issue when running Carla in synchronous mode with this bridge? What can go wrong or should I expect no difference?

Thank you for your time and consideration!

**Comment by TUMGEKA** [comment]
By default we are using synchronous mode: https://github.com/TUMFTM/Carla-Autoware-Bridge/blob/7914953a7ee6c9a94e57a5b2badff136143a49f2/launch/carla_aw_bridge.launch.py#L249
 The synchronized mode is recommended for this application, especially if your hardware is too slow. This mode ensures robust interaction between the AV software and the simulation. Furthermore, the CARLA Traffic Manager is designed to work in Sync. Mode: https://carla.readthedocs.io/en/latest/adv_traffic_manager/

No we are running it in sync mode

**Comment by YuqiHuai** [comment]
@TUMGEKA Thank you for the information!

**Comment by YuqiHuai** [comment]
@TUMGEKA I have 1 follow-up question. Does this bridge ensure Carla's simulation clock and Autoware's `/clock` are synchronized with each other?
