### ISSUE TITLE
Regarding the issue of vehicle location initialization in autoware and carla

### ISSUE THREAD

**Issue by Denghaoyuan123** [TUMFTM/Carla-Autoware-Bridge#22]
Thanks for giving such an excellent project.
I just have a simple problem that when I use "2D Pose Estimate" button in autoware to set the Car's position, why the Car in Carla changed first, and then in autoware?
I just echo two topics "/initialpose"  and "/sensing/gnss/pose_with_covariance", and find that Carla publishes the Gnss sensor msg continuously, but the "/initialpose" is published only one time when I use the "2D Pose Estimate" button.

And How Carla get the  autoware' s "/initialpose" topic msg to change the Position in Carla, where is the code about it?

**Comment by TUMGEKA** [comment]
Hey @Denghaoyuan123 we are using the standard feature of the carla ros bridge. It subscribes to the topic /initialpose and sets the position of the ego_vehicle based on it. The /initialpose topic can only be published manually using RVIZ. You just click on the 2D Pose Estimate button. Thi simultanously triggers teh reinitialization fo autoware, so Autoware tries to relocalize gloablly, thats why it takes more time.
