### ISSUE TITLE
There is no image after using view:=true

### ISSUE THREAD

**Issue by xiaoc88** [TUMFTM/Carla-Autoware-Bridge#24]
Hi,I tried to fill in view:=true and there was no image.It is not clear whether this is related to the error in the red box?
![2024-07-03_14-37](https://github.com/TUMFTM/Carla-Autoware-Bridge/assets/170789842/fbdc7bfd-5a3e-485c-8a2e-996ced0d6ca1)

**Comment by Robotics010** [comment]
Hi @xiaoc88 
I also don’t see this third-view window created.

I think the docker container does not have `pygame` python module installed. That is why you don’t see it.

**Comment by xiaoc88** [comment]
@Robotics010 pygame has been installed, Otherwise, the program will run error.autoware and bridge are normal, but the image is not visible.
command:pip3 install pygame
![image](https://github.com/TUMFTM/Carla-Autoware-Bridge/assets/170789842/4b25b0d1-7c4f-4490-8b59-d59f3cc50035)

**Comment by xiaoc88** [comment]
@Robotics010 May I ask whether the display using view:=true is normal?

**Comment by dilloncsr** [comment]
https://github.com/TUMFTM/Carla-Autoware-Bridge/issues/5#issue-2174359557

This should resolve your issue.

**Comment by Stuare8** [comment]
@dilloncsr @Robotics010 Thank you very much, this problem has indeed been resolved. https://github.com/TUMFTM/Carla-Autoware-Bridge/issues/5#issue-2174359557

**Comment by xiaoc88** [comment]
> [#5 (comment)](https://github.com/TUMFTM/Carla-Autoware-Bridge/issues/5#issue-2174359557)
> 
> This should resolve your issue.

@dilloncsr @Robotics010  Thank you very much, this problem has indeed been resolved.

**Comment by Cherrrray** [comment]
may I ask if your Carla_autoware_bridge is in docker or not? I use the docker version, but it don't have pygame which results in the failure and error of view:=true.
