### ISSUE TITLE
Can't pull the autoware-universe:humble-2024.01-cuda-amd64 image.

### ISSUE THREAD

**Issue by MarioAlmelaUMH** [TUMFTM/Carla-Autoware-Bridge#26]
Hi, I'm working on an application that requires an autoware 2024.01 docker image. Before, I could download it by using: `docker pull ghcr.io/autowarefoundation/autoware-universe:humble-2024.01-cuda-amd64`, however, since last Friday I'm unable to. Docker shows the following error:

![error docker](https://github.com/user-attachments/assets/8b7f3f98-8f02-45ba-83d7-15353266aa91)

I never needed to login before to use this command or to download this image, also non-Autoware images do work properly, like the default hello-world image used to test docker itself.

The command provided in the bridge's README file no longer works for me. Could it be that the 2024.01 image has been removed by Autoware? Is there any other compatible image I can use instead?

Thanks for your help.

**Comment by wizardwwc** [comment]
I also encountered the same issue.

**Comment by MarioAlmelaUMH** [comment]
Apparently, Autoware images have been moved to a different registry. I opened a discussion in their github, where they showed the new links for the images: https://github.com/orgs/autowarefoundation/discussions/4990#discussioncomment-10108843

**Comment by chuckjpn** [comment]
I solved it to delete "-universe"
