### ISSUE TITLE
Singularity support

### ISSUE THREAD

**Issue by abol-karimi** [TUMFTM/Carla-Autoware-Bridge#3]
Is it possible to run your setup in Singularity? I want to run it on an HPC cluster which doesn't allow Docker.

**Comment by TUMGEKA** [comment]
Unfortunately nobody in our team works with Singularity. Looking at the official documentation it seems to be possible to integrate docker images into Singularity. [](https://docs.sylabs.io/guides/2.6/user-guide/singularity_and_docker.html)
