### ISSUE TITLE
Unable to localize (NDT align server failed) 

### ISSUE THREAD

**Issue by jz230-user** [TUMFTM/Carla-Autoware-Bridge#31]
Hello! I had reproduced this project successfully with its initial release and everything worked fine! Just this week when I launch the carla-autoware system it seems to be unable to localize the vehicle and the initial pose cannot be received.  I am getting the following error. I have also tried rebuilding the packages that are creating the issue and also created a new system with the updated docker image. The issue seems to persist in the new version of aw as well. Please help! Thanks in advance

error in the terminal:
![issue github](https://github.com/user-attachments/assets/ddc5e9fc-4a8c-40c6-8c55-c34162a90eb6)

**Comment by danicannt** [comment]
How did you solve this?
@jz230-user

**Comment by jz230-user** [comment]
@danicannt It was an NVIDIA driver issue, after updating the NVIDIA driver to 545 it seemed to work fine again.
