### ISSUE TITLE
No such file or directory: '/root/autoware_data/lidar_centerpoint/centerpoint_tiny_ml_package.param.yaml'

### ISSUE THREAD

**Issue by Lkaho** [TUMFTM/Carla-Autoware-Bridge#34]
I've been following a tutorial video to modify the launch files in Autoware. However, after making the changes, I encountered an issue when running Autoware 2024.06, as shown in the attached screenshot. Interestingly, I did not face this issue with the Autoware 2024.04 version.
![image](https://github.com/user-attachments/assets/9393ae71-ba22-45b3-a472-08980fd4c092)

Additionally, when I add the required files in the suggested directory, Autoware can launch, but it doesn't receive any sensor information, as shown in the screenshot below.
![image](https://github.com/user-attachments/assets/339bde1c-ed41-4a8e-bb7d-401d53837af3)

Could you please advise on how to resolve this problem? Any help would be greatly appreciated. Thank you!

**Comment by rivergold** [comment]
@Lkaho Have you solved this problem?
