### ISSUE TITLE
Fix Control for Autoware.Universe Releases newer than 2024.01

### ISSUE THREAD

**Issue by TUMGEKA** [TUMFTM/Carla-Autoware-Bridge#7]
Autoware underwent significant control changes after Version 2024.01. These modifications have resulted in strong braking during curves. This issue should be thoroughly investigated and optimized. Additionally, we plan to integrate a vehicle interface for our Carla vehicle in the long term.

**Comment by TUMGEKA** [comment]
Multiple people noticed weird behavior after the latest control fixes. I thinks its related to these changes: https://github.com/TUMFTM/ros-bridge/commit/d9e3b22a94cf2ff2b49f2df0b69ae05457d3c3eb
I will revert them for now
![image](https://github.com/TUMFTM/Carla-Autoware-Bridge/assets/110600488/4cf37e7a-9e28-4b12-9265-1f50b700077e)

**Comment by TUMGEKA** [comment]
@baskKeT Can you look into that and test it again. I think the updated angle cahnges are sufficient enough to fix that issue.

**Comment by baskKeT** [comment]
@TUMGEKA Yes, I'm already on it.
