### ISSUE TITLE
vehicle_state_report missing

### ISSUE THREAD

**Issue by TUMGEKA** [TUMFTM/Carla-Autoware-Bridge#9]
Autoware expects the vehicle_state_report message. This essentially only says that the vehicle will or will not execute a control message in the current state. We should integrate this message into our bridge so that the warning no longer appears

**Comment by xiaoc88** [comment]
I had the same problem,The auto button is always gray and cannot be clicked.
![image](https://github.com/TUMFTM/Carla-Autoware-Bridge/assets/170789842/a73f1304-1786-4862-9727-03dc7be581eb)
